Adds Learn segment with 4 main sections
massalabs/docu-dev pull request #34
Opened 2023-05-16 19:35 UTC by longgamma-massa

The Learn section is an improvement of [Massa's Architecture section](https://docs.massa.net/en/latest/general-doc/architecture.html).

Planned sections in order:

1. Basic concepts  (previous Introduction), which needs improvements in content. I instructed what needs to be done..
2. Node Architecture (previous Architecture) which needs validation as I shortened some content where I could.
3. Operation lifecycle (as it was, no need to fix it)
4. Consensus quality initiatives - a new section for which I planned to include: 
- Endorsements (needs core validation as I shortened some parts and also needs their check since they made some changes to endorsements object)
- Slashing (needs a full write up)
- Node banning (needs a full write up). The idea with this new section is to unify all (dis)incentives in our consensus in one place where you can learn how we maximize the quality of our network. 

--- 
All needed changes/needed content or checks I showed in Admonition  :::danger 

To do:
- [ ] Validate my summaries and planned structure;
- [ ] Add all diagrams and tables as indicated in the code;
- [ ] Add equations using Katex for parts of the code  in ``
- [ ] Fill all links that currently don't exist.
- [ ] Improve content specified in Admonitions -> danger mode.

2023-05-19 10:32 UTC, longgamma-massa commented on docs/learn/architecture/consensus-quality.mdx
> +
In the current list of future improvements at [the end of the Endorsement section](https://docs.massa.net/en/latest/general-doc/architecture/endorsements.html#future-features), there are some issues that are merged, hence we need to make sure this structure is up to date. 
- @AurelienFT please review and validate content and the table structure of this section

2023-05-19 10:32 UTC, longgamma-massa commented on docs/learn/architecture/consensus-quality.mdx
> +### Incentives and penalties
Above part is the summary of the 'initiatives and penalties' section given [here](https://docs.massa.net/en/latest/general-doc/architecture/endorsements.html#incentives-and-penalties). 
- Needs validation by @AurelienFT. If not good, we need a shorter version of the current Massa docs section.

2023-05-19 11:27 UTC, longgamma-massa commented on docs/learn/architecture/operation-lifecycle.mdx
> +# Operation lifecycle
need a validation that this section is still up to date. It is a copy/paste of the [current docs](https://docs.massa.net/en/latest/general-doc/architecture/archi-global.html#operation-lifecycle). 

@AurelienFT

2023-05-22 08:14 UTC, AurelienFT commented on docs/learn/architecture/architecture.mdx
> +factories via a `gRPC (and JSON RPC?)` protocol.
You can mention both gRPC isn't fully ready to take over JSON-RPC.

2023-05-22 08:38 UTC, AurelienFT commented on docs/learn/architecture/consensus-quality.mdx
> +### Incentives and penalties
This one is ok

2023-05-22 09:11 UTC, gregLibert commented
> @gregLibert:
> 
> Content of Learn part is ready to be filled by intern for:
> 
> * [ ]  links
> * [ ]  equations with Katex
> * [ ]  Diagrams and images as marked with Admonition :::danger
> * [ ]  reorganize the sidebar in case we go with 1 concept per page, like Block, Operation, etc.
> 
> Note: I created sections that need write up by Core team and marked with - to do, so they can navigate easier. Also lines have been broken for easier navigation in the docu.

@windushka Can you please help us here ? feel free to poing @longgamma-massa or myself if you need some help!

2023-05-22 13:13 UTC, AurelienFT commented on docs/learn/architecture/consensus-quality.mdx
> +
I made comments on things that I didn't like. So we can consider this part as reviewed

2023-05-22 13:13 UTC, AurelienFT commented on docs/learn/architecture/consensus-quality.mdx
> +
I made comments on things that I didn't like. So we can consider this part as reviewed

2023-05-22 13:13 UTC, AurelienFT commented on docs/learn/architecture/consensus-quality.mdx
> +### Endorsement lifecycle
I made comments on things that I didn't like. So we can consider this part as reviewed

2023-05-22 16:15 UTC, longgamma-massa commented on docs/learn/architecture/consensus-quality.mdx
> +the endorsement producer draws for that slot. It attempts to create endorsements using the keypairs managed by its wallet.
I removed the sentence about the wallet and keys

2023-05-22 16:26 UTC, longgamma-massa commented
@gregLibert applied changes to content instructed by Aurelien.

2023-05-23 13:37 UTC, gregLibert requested changes

2023-05-23 13:37 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +the selection process [here](XXX TODO XXX), and the proof of stake sybil resistance mechanism [here](XXX TODO XXX)),
Links are missing

2023-05-23 13:37 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> + Learn more about Autonomouse Smart Conctracts [here](XXX TODO XXX)
```suggestion
 Learn more about Autonomouse Smart Contracts [here](XXX TODO XXX)
```
+ link is missing

2023-05-24 03:40 UTC, windushka commented on docs/learn/architecture/basic-concepts.mdx
> + Learn more about Autonomouse Smart Conctracts [here](XXX TODO XXX)
I suppose in the Tutorial page there should be a section dedicated to Autonomous Smart Contracts, explaining how to use them and this link redirecting to it?

2023-05-24 15:12 UTC, gregLibert requested changes

2023-05-24 15:12 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +</table>
Why not using markdown table with https://github.com/wataru-chocola/remark-extended-table remark module ?

The text will be more readable and easier to write also.

2023-05-24 15:12 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +</table>
same as above: you should use markdown table structure. this is also true for other tables.

2023-05-25 05:52 UTC, windushka commented on docs/learn/architecture/basic-concepts.mdx
> +</table>
Unfortunately, I tried installing this plugin and came to the conclusion that it's ESM which is not supported yet by Docusaurus, [see](https://docusaurus.io/docs/markdown-features/plugins#installing-plugins). I used this approach because in standard markdown tables I couldn't achieve to have one header for two columns, it would always keep the second column empty.

2023-05-25 05:53 UTC, windushka commented on docs/learn/architecture/basic-concepts.mdx
> +</table>
> @windushka I still have todo here. is it because a page is missing

I believe you were reviewing an outdated version

2023-05-26 10:08 UTC, gregLibert commented
@longgamma-massa can I merge this branch ?

2023-05-26 10:08 UTC, gregLibert approved these changes

2023-05-26 13:02 UTC, longgamma-massa commented
> @longgamma-massa can I merge this branch ?

@gregLibert @windushka 

The links for JSON RPC and GRPC are incorrect in the 'architecture' file -> 'API module' section. They lead to providers list instead of to pages where JSON RPC and GRPC documentation will be hosted, not the list of providers.

They rest is good to be merged (note: there are still subsections in text marked as 'to do' for Core's further work (issues are crearted).

2023-05-26 15:42 UTC, merged