adds Learn-ASC section
massalabs/docu-dev pull request #51
Opened 2023-06-05 15:27 UTC by longgamma-massa

To do:

- [ ] Review content as it is a summary of previous documentation section [here](https://docs.massa.net/en/latest/general-doc/autonomous-sc.html#introduction)
- [ ] Needs a check from core if [this section is still up to date](https://docs.massa.net/en/latest/general-doc/autonomous-sc.html#mechanism-in-massa-network). I also suggest making a diagram like in Operation Lifecycle (Learn - Architecture) section.
- [ ] Added use-cases. They need a check from @gregLibert or @qdrn. We can expand on them to make them more specific if you'd like. 
- [ ] Add some links to other sections (at the end of the file).
- [ ] Make this section a folder with files as indicated in the Introduction (TO-DO) section.

2023-06-15 12:52 UTC, qdrn requested changes

2023-06-15 12:52 UTC, qdrn commented on docs/learn/autonomous-sc.mdx
> +We already learned that autonomous smart contracts have the special ability to self wake-up and execute actions when specific
I'd remove this sentence, it doesn't add much given that this is specified just above.

2023-06-15 12:52 UTC, qdrn commented on docs/learn/autonomous-sc.mdx
> +This offers a wide range of compelling use-cases that were either impossible, too costly, or risky to do with benchmark
```suggestion
Autonomous smart contracts offers a wide range of compelling use-cases that were either impossible, too costly, or risky to do with benchmark 
```
If you remove the sentence above I would change the start of this one.

2023-06-15 12:52 UTC, qdrn commented on docs/learn/autonomous-sc.mdx
>  # Going further
Can you point to the build section for now and make an issue so that we update this part once we have a corresponding section in this doc ? So that we can merge this PR.

2023-06-15 12:53 UTC, qdrn commented
I also agree that it would be nice to have a diagram. This can be added in a followup issue.

2023-06-19 19:08 UTC, longgamma-massa commented
@gregLibert two things left to do (add a link, and make it a folder) from the PR description. Then you can merge.

@qdrn moved the section and diagram to-do into a new issue #81

2023-06-20 13:11 UTC, qdrn commented on docs/learn/autonomous-sc.mdx
> +this should be turned into a folder and have pages: Introduction, ASC on the Massa blockchain, Usecases, Going Further.
Please don't leave todo in the documentation. Make issues if you don't want to do it in this PR.

2023-06-21 07:25 UTC, gregLibert commented
> @gregLibert two things left to do (add a link, and make it a folder) from the PR description. Then you can merge.

done

2023-06-21 14:13 UTC, gregLibert approved these changes

2023-06-24 17:08 UTC, qdrn commented
I've made a proposal for this section. Let me know if that's okay with you @longgamma-massa and then we can merge!

2023-06-26 14:23 UTC, longgamma-massa commented
@qdrn can't approve my own PR, but it's a go from me

2023-06-26 15:20 UTC, qdrn approved these changes

2023-06-26 15:21 UTC, merged