add faucet doc
massalabs/docu-dev pull request #52
Opened 2023-06-05 17:49 UTC by lilyanB

2023-06-05 19:39 UTC, qdrn commented
I would put the faucet doc in the build section. As was decided here: https://github.com/massalabs/docu-dev/pull/29/files#diff-4d7e57f9b0d680e6756ea5f2117815ad177e0df673cf04cff626b4a34fd1ab11
The node section will quickly be outdated once the testnet is over with mainnet launch and we want to target developers.

2023-06-05 19:43 UTC, qdrn commented on docs/node/faucet.mdx
> +- Faucet allows for one request per day, ensuring fair distribution of rewards.
You can simply say that it's limited to one request per day. It's mostly for security rather than fairness. It's not a requirement so I would put it in a "note".

2023-06-05 19:43 UTC, qdrn commented on docs/node/faucet.mdx
> +# Faucet massa
There is an issue with ordering of sections. It goes from "#" to "###".

2023-06-06 05:44 UTC, lilyanB commented on docs/node/faucet.mdx
> +- Faucet allows for one request per day, ensuring fair distribution of rewards.
done

2023-06-06 05:47 UTC, lilyanB commented on docs/node/faucet.mdx
> +# Faucet massa
I have modified it. It goes from "#" to "##".

2023-06-06 14:36 UTC, qdrn requested changes
I've made small changes and made a comment. There is also a conflict to solve. Otherwise it looks ok.

2023-06-06 15:00 UTC, lilyanB commented on docs/build/faucet.mdx
> +# Faucets
I have pushed:
"Welcome to the Faucets page! Here, you'll find information about faucets on Massa networks, including their role in the blockchain ecosystem and how to receive coins from them."

2023-06-06 23:11 UTC, qdrn approved these changes

2023-06-06 23:11 UTC, merged

2023-06-06 23:12 UTC, qdrn commented
I've fix the sidebar to follow #29. And made a small change to the intro phrase. Thanks for the work @lilyanB !