adds storage costs to learn segment
massalabs/docu-dev pull request #54
Opened 2023-06-06 09:28 UTC by longgamma-massa

Added storage costs to Basic concepts and a new page Storage costs in the Architecture segment.
TO DO:
- [ ] review and update formulae by core as the Massa total supply changed (doubled) @AurelienFT @Eitu33 
- [ ] there is some content in ``` ``` that needs to use Katex format 
- [ ] add a link to Storage costs from Basic concepts (marked as to do)
- [ ] make the section Storage costs visible in the sidebar.

2023-06-08 07:54 UTC, gregLibert requested changes

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +In Massa, the ledger is distributed among all network nodes. To ensure smooth operation and enable node hosting at home (to reduce usually high entry barriers for potential node runners), it's essent
This sentence is too long.

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +In Massa, the ledger is distributed among all network nodes. To ensure smooth operation and enable node hosting at home (to reduce usually high entry barriers for potential node runners), it's essent
```
In Massa, the ledger is distributed among all network nodes.
```
is not clear, The reader can imagine that the ledger itself is distributed, each node having a sub part of it which is false.
My suggestion is:
```
In Massa, each network node maintains a full copy of the ledger.
```

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +Read more about storage costs (here)[todo link basic concepts].
```suggestion
Read more about storage costs (here)[docs/learn/architecture/storage-costs.mdx].
```

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +In the Massa network, the ledger is shared among all nodes, but to prevent the requirement of massive storage capacities like 100TB, a size limit of 1TB has been set. This limit is essential to encou
Same as above: "the ledger is shared among all nodes" is unclear to me.

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +In the Massa network, the ledger is shared among all nodes, but to prevent the requirement of massive storage capacities like 100TB, a size limit of 1TB has been set. This limit is essential to encou
You're explainin gthe same thing as above, are,'t you ?

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +Balances in the ledger are stored as varints, which means their size can vary. To avoid confusion, a fixed size of 8 bytes has been chosen for each balance. Therefore, the initial ledger entry for ad
this senetence is useless: "Balances in the ledger are stored as varints, which means their size can vary"

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +```address_size + balance_constant + bytecode_length + sum of (datastore_key_constant + datastore_value_size) * 0.00025```
Can't you use a mathematic display instead ?

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +It's important to note that the storage costs are always paid by the address that initiates the Application Binary Interface (ABI) call. For example, if the ABI functions "```set_bytecode```" or "```
```suggestion
It's important to note that the storage costs are always paid by the address that initiates the Application Binary Interface (ABI) call. For example, if the ABI functions [setBytecode](https://as-sdk.docs.massa.net/functions/setBytecode.html) or [setBycodeOf](https://as-sdk.docs.massa.net/functions/setBytecodeOf.html) are used, the associated storage costs will be charged to the address making the call.
```

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +Thus, if you create a new wallet using the Massa Client ```(massa-client)```, you can generate a secret key ```(wallet_generate_secret_key)```) and verify its address using the "```wallet_info``" fun
Unclear. You shoudl simply explain that a wallet without any operation is stored on the blockchain.

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +If a transfer of 0.005 Massa is received, the operation will fail.
Unclear, you should explain that if the amount of transfer on an unexisting address is lower than the amount of massa needed to create the address on the ledger, the operation will be refused

2023-06-08 07:54 UTC, gregLibert commented on docs/learn/architecture/storage-costs.mdx
> +In the case of a refund for storage costs, the address that receives the refund is the one that initiates the ABI call, which may differ from the address that initially paid for the storage.
Which ABI call ?

2023-06-08 10:32 UTC, longgamma-massa commented on docs/learn/architecture/storage-costs.mdx
> +In the Massa network, the ledger is shared among all nodes, but to prevent the requirement of massive storage capacities like 100TB, a size limit of 1TB has been set. This limit is essential to encou
Two different pages -> basic concepts has a few paragraphs to introduce the concept. The page Storage costs goes into details.

2023-06-15 22:13 UTC, qdrn commented on docs/learn/architecture/basic-concepts.mdx
> +Read more about storage costs (here)[docs/learn/architecture/storage-costs.mdx].
```suggestion

:::note
Read more about storage costs [here](/docs/learn/architecture/storage-costs).
:::
```
Link was broken

2023-06-16 09:12 UTC, gregLibert approved these changes

2023-06-16 09:22 UTC, merged