adds part of improvements for basic concepts
massalabs/docu-dev pull request #55
Opened 2023-06-06 13:11 UTC by longgamma-massa

Half of the improvements from the task #35 added here. 

To do:

- [ ] Review content by Aurelien
- [ ] Add some Katex-format to marked info with ``

2023-06-06 13:24 UTC, longgamma-massa commented on docs/learn/architecture/basic-concepts.mdx
> +An address on the Massa blockchain serves as your unique identity, granting you the ability to engage in various operations, store information, and exchange data with other participants. With an addr
@AurelienFT related to what we discussed in Discord's DMs, I created the list of the functionality for user address (these 3 paragraphs) and would like to do the same for SCs, and highlight the differences in functionalities.

2023-06-08 08:11 UTC, AurelienFT commented on docs/learn/architecture/basic-concepts.mdx
> +Each address on Massa has a public and private key associated with it. This is how messages can be signed and identity enforced.
This is only for user addresses

2023-06-08 08:11 UTC, AurelienFT commented on docs/learn/architecture/basic-concepts.mdx
> +For user addresses (AU), the hash calculation involves taking the Blake3 hash of the byte representation of the user's public key. This process ensures a unique and secure identification for each use
You talk about the precise format for sc address so maybe it's worth mentioning the version there also

2023-06-08 08:11 UTC, AurelienFT commented on docs/learn/architecture/basic-concepts.mdx
> +Smart contracts follow a different hash calculation than user addresses. It begins by constructing a byte array comprising various elements. This array consists of the slot represented in 5 bytes, wi
Note: This will change in testnet 24

2023-06-08 08:14 UTC, gregLibert requested changes

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +These technical decisions, including the exclusion of finalized state changes from ledger memory and the introduction of Storage Costs, play a crucial role in enabling the compact size of the ledger
isn't it already covered by the storage PR ?

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +An address on the Massa blockchain serves as your unique identity, granting you the ability to engage in various operations, store information, and exchange data with other participants. With an addr
Please add a new line at he end of each sentence. this will make raeding and review easier.

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +Addresses are generated using a specific format that includes a prefix ```A``` and a base58 encoding. The prefix distinguishes between user addresses, linked to a KeyPair, and smart-contract addresse
```suggestion
Addresses are generated using a specific format that includes a prefix `A` and a base58 encoding. The prefix distinguishes between user addresses, linked to a KeyPair, and smart-contract addresses, denoted by the prefixes `U` or `S` respectively.
```

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
> +:::
I have the feeling that you are saying the same thing three times.

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
>  Smart contracts are currently written in AssemblyScript, a stricter derivation from TypeScript, which is itself a
```suggestion
Smart contracts are currently written in AssemblyScript, a derivation from TypeScript, which is itself a 
```

2023-06-08 08:14 UTC, gregLibert commented on docs/learn/architecture/basic-concepts.mdx
>  ### Autonomous Smart Contract
Shouldn't we call that Autonomous Smart COntract execution ? because any SC can be executed autonomously.

2023-06-08 08:25 UTC, longgamma-massa commented on docs/learn/architecture/basic-concepts.mdx
> +For user addresses (AU), the hash calculation involves taking the Blake3 hash of the byte representation of the user's public key. This process ensures a unique and secure identification for each use
@AurelienFT which version should I mention? Maybe better to leave all SC-address related parts empty until testnet 24 updates are live?

2023-06-08 08:27 UTC, longgamma-massa commented on docs/learn/architecture/basic-concepts.mdx
> +These technical decisions, including the exclusion of finalized state changes from ledger memory and the introduction of Storage Costs, play a crucial role in enabling the compact size of the ledger
Structure: Basic concepts -> Storage costs introduce all concepts with key points. (same as ASC section for example) From Basic concepts we send users to read more for specific concepts, like the one I sent with storage PR. @gregLibert

2023-06-15 08:27 UTC, gregLibert approved these changes

2023-06-15 08:53 UTC, longgamma-massa commented
@gregLibert approve and merge pls

2023-06-15 09:11 UTC, merged