added testing & next steps to quickstart page
massalabs/docu-dev pull request #61
Opened 2023-06-08 08:26 UTC by windushka

2023-06-08 13:49 UTC, gregLibert requested changes

2023-06-08 13:49 UTC, gregLibert commented on docs/build/quickstart.mdx
> +## Testing Your Smart Contract
I'm not sure we need to do unit test in the quickstart. I was more thinking about doing end user test, accessing the front and seeing the greeting.
Wdyt?

2023-06-09 05:14 UTC, windushka commented on docs/build/quickstart.mdx
> +## Testing Your Smart Contract
I agree with you, unit testing might not be the most relevant to the goal of a quickstart guide. In that case I think it would be better to highlight more clearly the part with starting the application. I will add a few clarifying touches and we'll see how that turns out !

2023-06-12 07:47 UTC, gregLibert requested changes
One short small modification to do :-)

2023-06-12 07:47 UTC, gregLibert commented on docs/build/quickstart.mdx
> +1. Open your web browser and navigate to http://localhost:3000.
You should add a lint to simply the access to the local website.

2023-06-13 02:09 UTC, windushka commented on docs/build/quickstart.mdx
> +1. Open your web browser and navigate to http://localhost:3000.
Done, added a hyperlink

2023-06-13 08:53 UTC, gregLibert approved these changes

2023-06-13 08:54 UTC, merged