64 list packages versions and network compatibility
massalabs/docu-dev pull request #72
Opened 2023-06-16 12:56 UTC by Ben-Rey

This is a first proposition on how to display versions

Version are stored in a json located in a github gist. For test purpose I created one on my account : https://gist.github.com/Ben-Rey/9f475f1c5e8e0f78fa1570a727eef344

Why did we use a json ?
- This json will allow us to centralise versions informations in a single place.
- We could directly update this json (so by extension the doc) using ce CI when releasing a new project
- The JSON file can serve as a reliable data source for test repositories responsible for testing projects across different network

2023-06-16 13:28 UTC, gregLibert commented
@ben I have the feeling that this information should be in the Networks & Faucets (build section). Hence you will be able to have everything you need to connect to a network at the same place.

We can also duplicate the information to multiple pages if the source is the same :-)

@qdrn

2023-06-16 14:01 UTC, gregLibert commented on src/components/versions-table.tsx
> +      <div>
You should remove useless div:
```suggestion
  <>
```

2023-06-16 14:06 UTC, gregLibert commented on src/components/versions-table.tsx
> +                ))}
int the ma it's a compatibility, not compatibilities:
```suggestion
              <td>{project.title}</td>
              {project.compatibilities.map((comp) => (
                <td key={comp.network}>{comp.version}</td>
              ))}
```

2023-06-16 14:07 UTC, gregLibert commented on src/components/versions-table.tsx
> +                </td>
You should use a code bloc isntead:
```suggestion
              <td>
                <CodeBlock className="language-bash">
                  {getInstall(project, "buildnet")}
                </CodeBlock>
              </td>
```

2023-06-16 14:08 UTC, gregLibert commented on src/components/versions-table.tsx
> +    </div>
Remove useless trailing div:
```suggestion
    </>
```

2023-06-16 14:08 UTC, gregLibert commented on src/utils/helpers.tsx
> +};
useless

2023-06-16 19:05 UTC, Ben-Rey commented on src/components/versions-table.tsx
> +  }, []);
Done

2023-06-16 19:06 UTC, Ben-Rey commented on src/components/versions-table.tsx
> +    return `${project.install}@${compatibility.version}`;
Done

2023-06-16 19:06 UTC, Ben-Rey commented on src/components/versions-table.tsx
> +    return <div></div>;
done

2023-06-16 19:25 UTC, Ben-Rey commented on src/components/versions-table.tsx
> +  "https://gist.githubusercontent.com/Ben-Rey/9f475f1c5e8e0f78fa1570a727eef344/raw/gistfile1.txt";
Sorry, not sure to get the question. 
The JSON should be stored in a gist in massa organisation.
The link should stay the same so I can put it in a constants file

2023-06-17 07:00 UTC, qdrn commented
> @ben I have the feeling that this information should be in the Networks & Faucets (build section). Hence you will be able to have everything you need to connect to a network at the same place.
> 
> We can also duplicate the information to multiple pages if the source is the same :-)
> 
> @qdrn wdyt?

Yes, I think it makes more sense to put it in the network page and to put a note on the SDK page that link that links to it (or duplicate if you think it's better).

Overall I like the proposal that you made of having this json file that can be automatically updated. Much less error prone and much more convenient once setup!

Design is simple but good enough imo. We can have someone with more expertise go through all the designs once we are done with a first version (and done with more urgent matters!).

Congrats!

2023-06-19 07:46 UTC, gregLibert commented on src/components/versions-table.tsx
> +  "https://gist.githubusercontent.com/Ben-Rey/9f475f1c5e8e0f78fa1570a727eef344/raw/gistfile1.txt";
But right now the gist file 1 is in your personal account, right ?

2023-06-19 08:10 UTC, Ben-Rey commented on src/components/versions-table.tsx
> +  "https://gist.githubusercontent.com/Ben-Rey/9f475f1c5e8e0f78fa1570a727eef344/raw/gistfile1.txt";
Yes we need to create one with the massa account, sorry if I forgot to mention it. Then we'll update the URL.
Who can create a gist in massa organisation ?

2023-06-19 08:11 UTC, gregLibert approved these changes
Sounds good to me. Except for the fact that the piece of information should also be present in the network and faucet section

2023-06-19 18:03 UTC, qdrn commented
I think it's better like this, thanks!

2023-06-21 09:40 UTC, qdrn requested changes
Let's put the json in a file in this project that will be updated by the CI of the different projects as discussed.

2023-06-21 10:19 UTC, Ben-Rey commented
> Let's put the json in a file in this project that will be updated by the CI of the different projects as discussed.

I need to put this pr on hold for 1 day or 2 because we found a way to use tags so the developer will just have to do npm install massalabs/massa-web3@buildnet or massalabs/massa-web3@testnet or massalabs/massa-web3@latest ...
I just need the time to implement it on each repo

2023-06-21 10:25 UTC, Ben-Rey commented
> > Let's put the json in a file in this project that will be updated by the CI of the different projects as discussed.
> 
> I need to put this pr on hold for 1 day or 2 because we found a way to use tags so the developer will just have to do npm install massalabs/massa-web3@buildnet or massalabs/massa-web3@testnet or massalabs/massa-web3@latest ... I just need the time to implement it on each repo



> Let's put the json in a file in this project that will be updated by the CI of the different projects as discussed.

@julienbrs will check all versions to make sure we're providing the right information, then I'll put in the JSON.

2023-06-21 10:28 UTC, qdrn commented
Yeah no problem just keeping track! Thanks for the info.

2023-07-12 15:26 UTC, qdrn requested changes

2023-07-12 15:26 UTC, qdrn commented on docs/build/networks-faucets.mdx
> +<VersionsTable />
There's an issue here. See CI also.

2023-07-12 15:26 UTC, qdrn commented on docs/build/sdk.mdx
> +<VersionsTable />
Same here.

2023-07-24 14:51 UTC, qdrn approved these changes

2023-07-24 14:51 UTC, merged